### ISSUE TITLE
create docker-compose.yaml

### ISSUE THREAD

**Issue by AstralisCode** [AstralisCode/sdk-fbanalyze#1]
- [ ] service for api-fbanalyze
- [ ] service for api-eventhandler

**Comment by holms** [comment]
- [x] Finish these tickets first: 

https://github.com/AstralisCode/api-fbanalyze/issues/1
https://github.com/AstralisCode/api-eventlogger/issues/1
https://github.com/AstralisCode/api-fbanalyze/issues/2
https://github.com/AstralisCode/api-eventlogger/issues/3

- [x] Add `api-fbanalyze` and `api-eventlogger`  to  service of `docker-compose.yaml`
- [x] Launch the project with docker-compose make sure you can access each service in your browser, only then do a commit

**Comment by AstralisCode** [comment]
> * [ ]  service for api-fbanalyze
> 
>     * [ ]  service for api-eventhandler

Thank you for your comment.
Do I add these services to **the same docker-compose.yaml** intended for **sdk-fbanalyze** file analogically to **app.py**, which is already placed into the current docker-compose.yaml?
Also, does the sequence of placing the app /  service for api-fbanalyze /   service for api-eventhandler  matter if they supposed to be placed in the same document?

**Comment by holms** [comment]
Please explain what's  the purpose of docker-compose and compose yaml file? What problem does it solves?

**Comment by AstralisCode** [comment]
Docker Compose allows to define and launch complex multi-container app architectures all from one master configuration file. It launches different containers in one go and lets you run your app. It regulates separate services' connections and dependencies, port mapping, environment variables, volumes to mount, networks between each of the containers.

**Comment by holms** [comment]
So what does "service" block do in docker-compose.yaml file?

**Comment by AstralisCode** [comment]
It serves as an introduction point to list the services, their used ports, networks and dependencies, etc.

**Comment by holms** [comment]
Great so let's define our two microservices to that block. This should be done only once you've completed dockerfiles and app.py for both microservices
